baseURL = "https://gabicavalcante.github.io/"
languageCode = "en-us"
publishDir = "public"
theme = "hugo-theme-console"
title = "gabi cavalcante" 

[params]
  # Cutting off the page title to two chars for mobile (console-demo -> co)
  titleCutting = true

  [[params.navlinks]]
  name = "about/"
  url = "about/"

  [[params.navlinks]]
  name = "posts/"
  url = "posts/"